/**
 * constants.js - Phase 4.3 Canonical Attestation Constants
 *
 * Shared across all three lanes (Archivist, SwarmMind, Library).
 */

const path = require('path');

const TRUST_STORE_PATH =
  process.env.ATTESTATION_TRUST_STORE ||
  path.join('S:', 'Archivist-Agent', 'lanes', 'broadcast', 'trust-store.json');

const TRUST_STORE_VERSION = '1.0';

const MIGRATION_MODE = {
  DUAL: 'dual',
  HMAC_ONLY: 'hmac-only',
  RSA_ONLY: 'rsa-only'
};

const VERIFY_REASON = {
  VERIFIED: 'VERIFIED',
  SCHEMA_MISMATCH: 'SCHEMA_MISMATCH',
  TRUST_STORE_MISSING: 'TRUST_STORE_MISSING',
  UNKNOWN_LANE: 'UNKNOWN_LANE',
  KEY_NOT_FOUND: 'KEY_NOT_FOUND',
  KEY_ID_MISMATCH: 'KEY_ID_MISMATCH',
  KEY_REVOKED: 'KEY_REVOKED',
  INVALID_KEY: 'INVALID_KEY',
  UNSUPPORTED_ALGORITHM: 'UNSUPPORTED_ALGORITHM',
  MISSING_SIGNATURE: 'MISSING_SIGNATURE',
  MISSING_LANE: 'MISSING_LANE',
  MISSING_HMAC: 'MISSING_HMAC',
  SIGNATURE_MISMATCH: 'SIGNATURE_MISMATCH',
  LANE_MISMATCH: 'LANE_MISMATCH',
  DEPRECATED_HMAC: 'DEPRECATED_HMAC',
  MIGRATION_HMAC_ONLY: 'MIGRATION_HMAC_ONLY',
  VERIFICATION_ERROR: 'VERIFICATION_ERROR',
  QUARANTINED: 'QUARANTINED',
  QUARANTINE_RELEASED: 'QUARANTINE_RELEASED',
  QUARANTINE_MAX_RETRIES: 'QUARANTINE_MAX_RETRIES'
};

const ALG_MAP = {
  'rsa-sha256': 'RSA-SHA256',
  'RS256': 'RSA-SHA256',
  'rsa_sha256': 'RSA-SHA256'
};

const QUARANTINE_MAX_RETRIES = 3;
const QUARANTINE_BACKOFF_MS = 5000;
const QUARANTINE_LOG_PATH = path.join('S:', 'Archivist-Agent', 'logs', 'quarantine.log');
const HANDOFF_SIGNAL_FILE = 'AGENT_HANDOFF_REQUIRED.md';

module.exports = {
  TRUST_STORE_PATH,
  TRUST_STORE_VERSION,
  MIGRATION_MODE,
  VERIFY_REASON,
  ALG_MAP,
  QUARANTINE_MAX_RETRIES,
  QUARANTINE_BACKOFF_MS,
  QUARANTINE_LOG_PATH,
  HANDOFF_SIGNAL_FILE
};
